import type { Conversation } from './types'

export const demoConversations: Conversation[] = [
  {
    id: '1',
    name: 'Maya Chen',
    handle: '@maya',
    avatar: '/avatar-default.jpg',
    lastMessage: 'The new seed protocol is amazing! 🌱',
    lastMessageTime: '2m',
    unreadCount: 2,
    encrypted: true,
    online: true,
    peerCount: 3,
    verified: true,
    fingerprint: 'A3:F2:91:0B:4C:77:D8:E1:33:9A:5F:12:BB:88:00:7D',
    category: 'active',
    messages: [
      {
        id: 'm1',
        senderId: 'them',
        text: 'Hey! Have you tried the new seed distribution protocol?',
        type: 'text',
        timestamp: '10:32 AM',
        encrypted: true,
        selfDestruct: false,
        read: true,
        delivered: true,
      },
      {
        id: 'm2',
        senderId: 'me',
        text: 'Not yet — is it faster than the old gossip mesh?',
        type: 'text',
        timestamp: '10:33 AM',
        encrypted: true,
        selfDestruct: false,
        read: true,
        delivered: true,
      },
      {
        id: 'm3',
        senderId: 'them',
        text: 'Way faster. My chunks synced in under 30 seconds.',
        type: 'text',
        timestamp: '10:35 AM',
        encrypted: true,
        selfDestruct: false,
        read: true,
        delivered: true,
      },
      {
        id: 'm4',
        senderId: 'them',
        text: 'The new seed protocol is amazing! 🌱',
        type: 'text',
        timestamp: '10:36 AM',
        encrypted: true,
        selfDestruct: false,
        read: false,
        delivered: true,
      },
      {
        id: 'm5',
        senderId: 'them',
        text: 'Also the encryption overhead dropped by half.',
        type: 'text',
        timestamp: '10:36 AM',
        encrypted: true,
        selfDestruct: false,
        read: false,
        delivered: true,
      },
    ],
  },
  {
    id: '2',
    name: 'River Oaks',
    handle: '@river',
    avatar: '/avatar-default.jpg',
    lastMessage: '🔥 This message will self-destruct',
    lastMessageTime: '1h',
    unreadCount: 1,
    encrypted: true,
    online: false,
    lastSeen: '3h ago',
    peerCount: 5,
    verified: true,
    fingerprint: 'B7:11:CC:99:22:AA:44:FF:66:EE:88:DD:33:77:55:00',
    selfDestruct: true,
    category: 'offline',
    messages: [
      {
        id: 'r1',
        senderId: 'them',
        text: 'I have the docs you asked for. Sending via self-destruct.',
        type: 'text',
        timestamp: '9:15 AM',
        encrypted: true,
        selfDestruct: false,
        read: true,
        delivered: true,
      },
      {
        id: 'r2',
        senderId: 'them',
        text: 'Credentials: user=admin pass=seedling42 — burn after reading.',
        type: 'text',
        timestamp: '9:16 AM',
        encrypted: true,
        selfDestruct: true,
        selfDestructSeconds: 30,
        read: true,
        delivered: true,
      },
    ],
  },
  {
    id: '3',
    name: 'Solar Circle',
    handle: '@solar-circle',
    avatar: '/avatar-default.jpg',
    lastMessage: 'Meetup at the lighthouse this Friday?',
    lastMessageTime: 'Yesterday',
    unreadCount: 0,
    encrypted: false,
    online: true,
    peerCount: 12,
    verified: false,
    fingerprint: '',
    category: 'active',
    messages: [
      {
        id: 's1',
        senderId: 'them',
        text: 'Hey everyone — planning a local meetup!',
        type: 'text',
        timestamp: 'Yesterday',
        encrypted: false,
        selfDestruct: false,
        read: true,
        delivered: true,
      },
      {
        id: 's2',
        senderId: 'me',
        text: 'Count me in. What time?',
        type: 'text',
        timestamp: 'Yesterday',
        encrypted: false,
        selfDestruct: false,
        read: true,
        delivered: true,
      },
      {
        id: 's3',
        senderId: 'them',
        text: 'Meetup at the lighthouse this Friday?',
        type: 'text',
        timestamp: 'Yesterday',
        encrypted: false,
        selfDestruct: false,
        read: true,
        delivered: true,
      },
    ],
  },
  {
    id: '4',
    name: 'Anonymous Fox',
    handle: '@anon-fox',
    avatar: '/avatar-default.jpg',
    lastMessage: 'The forest listens.',
    lastMessageTime: '2d',
    unreadCount: 0,
    encrypted: true,
    online: false,
    lastSeen: '1d ago',
    peerCount: 2,
    verified: false,
    fingerprint: 'C1:99:DD:44:88:EE:22:77:55:33:AA:66:00:BB:FF:11',
    category: 'anonymous',
    messages: [
      {
        id: 'a1',
        senderId: 'them',
        text: 'The forest listens.',
        type: 'text',
        timestamp: '2 days ago',
        encrypted: true,
        selfDestruct: false,
        read: true,
        delivered: true,
      },
    ],
  },
  {
    id: '5',
    name: 'Jesse Bloom',
    handle: '@jesse',
    avatar: '/avatar-default.jpg',
    lastMessage: 'Can you review my profile widget?',
    lastMessageTime: '3d',
    unreadCount: 0,
    encrypted: false,
    online: false,
    lastSeen: '3d ago',
    peerCount: 1,
    verified: false,
    fingerprint: '',
    category: 'offline',
    messages: [
      {
        id: 'j1',
        senderId: 'them',
        text: 'Hey, I added a new custom HTML widget to my profile.',
        type: 'text',
        timestamp: '3 days ago',
        encrypted: false,
        selfDestruct: false,
        read: true,
        delivered: true,
      },
      {
        id: 'j2',
        senderId: 'them',
        text: 'Can you review my profile widget?',
        type: 'text',
        timestamp: '3 days ago',
        encrypted: false,
        selfDestruct: false,
        read: true,
        delivered: true,
      },
    ],
  },
  {
    id: '6',
    name: 'New Request',
    handle: '@unknown-seed',
    avatar: '/avatar-default.jpg',
    lastMessage: 'Wants to connect',
    lastMessageTime: '1w',
    unreadCount: 1,
    encrypted: true,
    online: true,
    peerCount: 1,
    verified: false,
    fingerprint: 'D0:11:22:33:44:55:66:77:88:99:AA:BB:CC:DD:EE:FF',
    category: 'active',
    messages: [],
  },
]

export const scrambleChars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*'
